# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: local-pv
# spec:
#   storageClassName: hostpath
#   claimRef:
#     namespace: default
#     name: database-persistent-volume-claim
#   capacity:
#     storage: 20Gi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   hostPath:
#     path: "/tmp"
# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  # volumeName: local-pv